---
name: Checks
on: [push]

jobs:
  test-lint:
    name: Test and Linting
    runs-on: ubuntu-20.04
    steps:
      - name: Login to docker hub
        uses: docker/login-action@v2
        with: username:${{secrets.DOCKERHUB_USER}}
          password:${{secrets.DOCKERHUB_TOKEN}}
      - name: Checout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm sh -c "flake8"
